# Use Node.js for building and running Vite
FROM node:20

WORKDIR /app

# Copy and install dependencies
COPY ./frontend/package*.json ./
RUN npm install

# Copy rest of the app
COPY ./frontend .

# Expose Vite dev port
EXPOSE 5173

# Run Vite dev server
CMD ["npm", "run", "dev", "--", "--host"]